on:
  push:
    branches:
      - master
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from another branch
        uses: actions/checkout@v2
        with:
          repository: Mamba1981/controlup_yuli_1
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version
      - name: Run tests
        run: |
          pytest
