on:
  push:
    branches:
      - main
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from another branch
        uses: actions/checkout@v2
        with:
          ref: controlup_yuli_1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
